### ISSUE TITLE
Chipmunk CLI cannot find main module

### ISSUE THREAD

**Issue by zauberparacelsus** [MyWorldLLC/Chipmunk#42]
When the Chipmunk CLI jar is run, the following error always occurs unless the -e flag is utilized:
`chipmunk.compiler.ModuleNotFoundException: module not found: Could not find main module main`

Previously I found this occured if there were multiple chipmunk scripts in a directory, but with further testing I found that this error occurs even when no other chipmunk scripts are in the same directory.

**Comment by danielperano** [comment]
I believe this is fixed by a065358. Previously, the `-e` flag defaulted to `main::main` causing the script to fail if the `-e` flag was not used and the main method was not in a module named `main`. That behavior has been removed, and the CLI first checks the `-e` flag: if `-e` is set, the main method *must* be correctly specified or the script will fail, if `-e` is not set, the entrypoint is assumed to be `main::main`. If the `main` module is not found or does not contain a main method, the CLI will search for and use the first module that defines a main method.

Can you confirm that the issue you've reported is now resolved? (Waiting for confirmation to close this issue.)

**Comment by zauberparacelsus** [comment]
Well, now there's a new issue.  If I run chipmunk in a directory with multiple scripts, it will *only* ever run the main method from the *last* script in the directory.  So in my example case, I have helloWorld.chp, mymath.chp, and test.chp, it will only run the main method from test.chp, since it is last in alphabetical order.

**Comment by danielperano** [comment]
And there's no `main` module in any of those files?

**Comment by zauberparacelsus** [comment]
Aye, none of them have a `main` module, but all of them have a `main()` function.

**Comment by danielperano** [comment]
So that's regardless of which file you pass as the script to run?

**Comment by danielperano** [comment]
I believe this is all resolved by d4b37cd.

**Comment by zauberparacelsus** [comment]
Forgot to leave a note here after discussing things on the Discord server.

The issue was not resolved by this fix.  If more than one script in a directory contains a `main()` method, then the `main()` from the last script in the directory is run.  Additionally, if any script in the directory contains a `main` module, then the `main()` method from that script is run instead.  Either case, it runs regardless of the script being targeted when invoking the chipmunk CLI.

**Comment by danielperano** [comment]
Fixed by 3104a6d.
